modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="${mod_repo}/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${project.version}"
displayName="${mod_name}"
displayURL="${mod_repo}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="icon.png"

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="architectury"
mandatory=true
versionRange="[${architectury_dependency},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bocchud"
mandatory=true
versionRange="[${bocchud_dependency},)"
ordering="NONE"
side="BOTH"