modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${mod_repo}/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${project.version}"
displayName="${mod_name}"
displayURL="${mod_repo}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="icon.png"

[[mixins]]
config = "minihudextra-common.mixins.json"

[[mixins]]
config = "minihudextra.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.20.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="architectury"
type="required"
versionRange="[${neoforge_architectury_dependency},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="bocchud"
type="required"
versionRange="[${neoforge_bocchud_dependency},)"
ordering="NONE"
side="BOTH"